[OPP-1521] Fjerne bruk av ISSO fra modia-robot-api
navikt/modia-robot-api pull request #67
Opened 2022-12-05 14:35 UTC by abrhanav

2022-12-05 14:41 UTC, nutgaard commented on src/main/kotlin/no/nav/Env.kt
> +    override val jwksUrl: String = getRequiredConfig("AZURE_APP_WELL_KNOWN_URL")
`ISSO_JWKS_URL` og `AZURE_APP_WELL_KNOWN_URL` peker ikke mot ekvivalente urler.

2022-12-06 13:01 UTC, Jesperpaulsen approved these changes
<img src="https://media1.giphy.com/media/tczJoRU7XwBS8/giphy.gif"/>

2022-12-08 14:35 UTC, nutgaard requested changes
Oppsettet for `Nom`/`NomClient` må tittes på for å unngå at det cachingen ikke forsvinner derifra.
Og tror `UtbetalingerClient` nå står uten authorization

2022-12-08 14:35 UTC, nutgaard commented on src/main/kotlin/no/nav/api/oppfolging/OppfolgingService.kt
> +    private fun nomClient(token: String) = nom.client(token)
Dette vil lage en ny `NomClient`  for vært kall til `hentVeileder`.

2022-12-08 14:35 UTC, nutgaard commented on src/main/kotlin/no/nav/api/oppfolging/Nom.kt
> +    fun client(token: String): NomClient = if (isNotProd()) {
Denne kan ikke være avhengig av `token` siden da må en ny `NomClient` lages for vært token vi ser i appen.
Det er ikke supert med tanke på ressursbruk og connectionpool, men også caching fra `CachedNomClient` vil bli borte ved en sånn tilnærming.

2022-12-08 14:35 UTC, nutgaard commented on src/main/kotlin/no/nav/Consumers.kt
> +    val nom: Nom
Bør nok fortsette å være `NomClient` her

2022-12-08 14:35 UTC, nutgaard commented on src/main/kotlin/no/nav/api/dialog/DialogRoutes.kt
> +    fun getPayload(call: ApplicationCall): DecodedJWT = checkNotNull(call.principal<JWTPrincipal>()?.payload as DecodedJWT) { "Could not extract payload from token" }
Denne kodesnutten ser ut til å være duplisert en del ganger.

Kan vi flytte den til ett felles sted, og evt gjøre noe alà;


```kotlin
fun ApplicationCall.getPrincipalJWT(): DecodedJWT = checkNotNull(call.principal<JWTPrincipal>()?.payload as DecodedJWT) {
  "Could not get JWT"
}
```

Da er det veldig enkelt med tanke på gjenbruk i andre settinger, f.eks om man ønsker å hente veileders ident.

Men token kan også enkelt hentes ut 
```kotlin
notarizedPost(Api.sendSporsmal) {
  val token = call.getPrincipalJWT().token
  call.respond(
    service.doSomething(token)
  )
}
```

2022-12-08 14:35 UTC, nutgaard commented on src/main/kotlin/no/nav/api/utbetalinger/UtbetalingerClient.kt
> +            AuthorizationInterceptor {
Denne vil vel ikke gjøre noe her? `AuthorizationInterceptor` er vel bare en klasse som blir nyet opp i dette tilfelle?

2022-12-09 09:16 UTC, nutgaard approved these changes

2022-12-09 11:23 UTC, merged